version: "3.9"

services:
  db:
    image: mariadb:11
    environment:
      MYSQL_ROOT_PASSWORD: root123
      MYSQL_DATABASE: comervial
      MYSQL_USER: dev
      MYSQL_PASSWORD: dev123
    ports:
      - "3307:3306"
    volumes:
      - db_data:/var/lib/mysql

    healthcheck:
      test: ["CMD", "mariadb-admin", "ping", "-h", "localhost"]
      interval: 5s
      timeout: 3s
      retries: 10

  web:
    build: .
    command: python manage.py runserver 0.0.0.0:8000
    volumes:
      - .:/app
    ports:
      - "8000:8000"
    depends_on:
      db:
        condition: service_healthy
    environment:
      DB_NAME: comervial
      DB_USER: dev
      DB_PASSWORD: dev123
      DB_HOST: db
      DB_PORT: 3306
      DEBUG: "True"

volumes:
  db_data:
