# Generated by Django 4.2.14 on 2025-12-01 17:57

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CustomerProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(blank=True, max_length=150, verbose_name='Nombre completo')),
                ('rut', models.CharField(blank=True, max_length=12, verbose_name='RUT')),
                ('phone', models.CharField(blank=True, max_length=20, verbose_name='Teléfono')),
                ('address', models.CharField(blank=True, max_length=255, verbose_name='Dirección')),
                ('comuna', models.CharField(blank=True, max_length=100, verbose_name='Comuna')),
                ('region', models.CharField(blank=True, choices=[('XV', 'Arica y Parinacota'), ('I', 'Tarapacá'), ('II', 'Antofagasta'), ('III', 'Atacama'), ('IV', 'Coquimbo'), ('V', 'Valparaíso'), ('RM', 'Región Metropolitana'), ('VI', "O'Higgins"), ('VII', 'Maule'), ('XVI', 'Ñuble'), ('VIII', 'Biobío'), ('IX', 'La Araucanía'), ('XIV', 'Los Ríos'), ('X', 'Los Lagos'), ('XI', 'Aysén'), ('XII', 'Magallanes')], max_length=10, verbose_name='Región')),
                ('country', models.CharField(default='Chile', editable=False, max_length=50, verbose_name='País')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='customer_profile', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Perfil de cliente',
                'verbose_name_plural': 'Perfiles de cliente',
            },
        ),
    ]
