# Generated by Django 4.2.14 on 2025-11-06 13:43

from decimal import Decimal
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CustomQuoteRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=120)),
                ('email', models.EmailField(max_length=254)),
                ('telefono', models.CharField(blank=True, max_length=40)),
                ('tipo', models.CharField(choices=[('mirror', 'Espejo'), ('window', 'Ventana')], max_length=16)),
                ('ancho_mm', models.PositiveIntegerField()),
                ('alto_mm', models.PositiveIntegerField()),
                ('cantidad', models.PositiveIntegerField(default=1)),
                ('marco', models.CharField(blank=True, choices=[('none', 'Sin marco'), ('aluminum', 'Marco aluminio'), ('wood', 'Marco madera')], max_length=16)),
                ('borde', models.CharField(blank=True, choices=[('polished', 'Borde pulido'), ('beveled', 'Biselado')], max_length=16)),
                ('cristal', models.CharField(blank=True, choices=[('tempered', 'Templado'), ('laminated', 'Laminado'), ('monolithic', 'Monolítico'), ('termopanel', 'Termopanel (DVH)')], max_length=16)),
                ('espesor_mm', models.CharField(blank=True, choices=[('3', '3 mm'), ('4', '4 mm'), ('5', '5 mm'), ('6', '6 mm')], max_length=2)),
                ('color_perfileria', models.CharField(blank=True, choices=[('blanco', 'Blanco'), ('titanio', 'Titanio'), ('madera', 'Folio madera')], max_length=16)),
                ('ubicacion', models.CharField(blank=True, max_length=120)),
                ('detalles', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('aprobado', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='QuoteRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=120)),
                ('email', models.EmailField(max_length=254)),
                ('telefono', models.CharField(blank=True, max_length=50)),
                ('categoria', models.CharField(blank=True, max_length=120)),
                ('mensaje', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('total_price', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12)),
                ('status', models.CharField(default='En revisión', max_length=64)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('quote', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='order', to='quotes.customquoterequest')),
            ],
        ),
    ]
