# Generated by Django 4.2.14 on 2025-12-06 21:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0005_product_description'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='material',
            field=models.CharField(choices=[('PVC', 'PVC'), ('ALU', 'Aluminio'), ('CRI', 'Cristal')], max_length=3),
        ),
    ]
