# Generated by Django 4.2.14 on 2025-10-02 17:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120, unique=True)),
                ('slug', models.SlugField(blank=True, max_length=140, unique=True)),
            ],
            options={
                'verbose_name': 'Categoría',
                'verbose_name_plural': 'Categorías',
                'ordering': ('name',),
            },
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=180)),
                ('slug', models.SlugField(blank=True, max_length=200, unique=True)),
                ('material', models.CharField(choices=[('PVC', 'PVC'), ('ALU', 'Aluminio')], max_length=3)),
                ('glass_type', models.CharField(choices=[('LAM', 'Laminado'), ('TEM', 'Templado'), ('MON', 'Monolítico'), ('TERM', 'Termopanel')], max_length=4)),
                ('thickness', models.CharField(choices=[('3', '3 mm'), ('4', '4 mm'), ('5', '5 mm')], max_length=2)),
                ('color', models.CharField(choices=[('WOOD', 'Folio madera'), ('TIT', 'Titanio'), ('WHT', 'Blanco'), ('RED', 'Rojo')], max_length=5)),
                ('price', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('image', models.ImageField(blank=True, null=True, upload_to='products/')),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='products', to='catalog.category')),
            ],
            options={
                'ordering': ('-created_at',),
                'indexes': [models.Index(fields=['material', 'glass_type', 'thickness', 'color'], name='catalog_pro_materia_0ed177_idx'), models.Index(fields=['is_active'], name='catalog_pro_is_acti_14fc6b_idx')],
            },
        ),
    ]
